micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    basic-auth:
      enabled: true

akhq:
  connections:
    local-kafka: # A friendly name for your cluster
      properties:
        bootstrap.servers: "kafka-broker-0:9092"
        
        security.protocol: SSL 
        ssl.truststore.location: /etc/akhq/secrets/truststore.jks
        ssl.truststore.password: "${AKHQ_TRUSTSTORE_PASSWORD}" 
        ssl.endpoint.identification.algorithm: https 
        ssl.keystore.location: /etc/akhq/secrets/kafka-akhq-keystore.jks 
        ssl.keystore.password: "${AKHQ_KEYSTORE_PASSWORD}" 

      connect:
        - name: "kafka-connect" 
          url: "https://kafka-connect:8083" 
          ssl-trust-store: /etc/akhq/secrets/truststore.jks
          ssl-trust-store-password: "${AKHQ_TRUSTSTORE_PASSWORD}"
          ssl-key-store: /etc/akhq/secrets/kafka-akhq-keystore.jks 
          ssl-key-store-password: "${AKHQ_KEYSTORE_PASSWORD}"

  security:
    default-group: no-roles 
    basic-auth:
    - username: admin
      password: "eb19cc056d0600178f1b0bd5ab14b9a31d71dd15abf879f7bda20139a7a570f9" 
      groups:
      - admin
    - username: reader
      password: "eb19cc056d0600178f1b0bd5ab14b9a31d71dd15abf879f7bda20139a7a570f9" 
      groups:
      - reader